# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AddMediaToAlbum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'AddMediaToAlbum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x41\x64\x64MediaToAlbum.proto\x12\x07gphotos\"\xa6\x02\n\x0f\x41\x64\x64MediaToAlbum\x12\x12\n\nmedia_keys\x18\x01 \x03(\t\x12\x17\n\x0f\x61lbum_media_key\x18\x02 \x01(\t\x12\x33\n\x06\x66ield5\x18\x05 \x01(\x0b\x32#.gphotos.AddMediaToAlbum.Field5Type\x12\x38\n\x0b\x64\x65vice_info\x18\x06 \x01(\x0b\x32#.gphotos.AddMediaToAlbum.Field6Type\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\x1a\x1c\n\nField5Type\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x03\x1a\x46\n\nField6Type\x12\r\n\x05model\x18\x03 \x01(\t\x12\x0c\n\x04make\x18\x04 \x01(\t\x12\x1b\n\x13\x61ndroid_api_version\x18\x05 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AddMediaToAlbum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDMEDIATOALBUM']._serialized_start=35
  _globals['_ADDMEDIATOALBUM']._serialized_end=329
  _globals['_ADDMEDIATOALBUM_FIELD5TYPE']._serialized_start=229
  _globals['_ADDMEDIATOALBUM_FIELD5TYPE']._serialized_end=257
  _globals['_ADDMEDIATOALBUM_FIELD6TYPE']._serialized_start=259
  _globals['_ADDMEDIATOALBUM_FIELD6TYPE']._serialized_end=329
# @@protoc_insertion_point(module_scope)
