# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CommitUpload.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CommitUpload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x43ommitUpload.proto\x12\x07gphotos\"\x9e\x04\n\x0c\x43ommitUpload\x12\x30\n\x06\x66ield1\x18\x01 \x01(\x0b\x32 .gphotos.CommitUpload.Field1Type\x12\x30\n\x06\x66ield2\x18\x02 \x01(\x0b\x32 .gphotos.CommitUpload.Field2Type\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\x0c\x1a\xd1\x02\n\nField1Type\x12;\n\x06\x66ield1\x18\x01 \x01(\x0b\x32+.gphotos.CommitUpload.Field1Type.Field1Type\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x11\n\tsha1_hash\x18\x03 \x01(\x0c\x12;\n\x06\x66ield4\x18\x04 \x01(\x0b\x32+.gphotos.CommitUpload.Field1Type.Field4Type\x12\x0f\n\x07quality\x18\x07 \x01(\x03\x12\x0f\n\x07\x66ield10\x18\n \x01(\x03\x12\x0f\n\x07\x66ield17\x18\x11 \x01(\x03\x1a,\n\nField1Type\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x03\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x0c\x1a\x42\n\nField4Type\x12$\n\x1c\x66ile_last_modified_timestamp\x18\x01 \x01(\x03\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x03\x1a\x46\n\nField2Type\x12\r\n\x05model\x18\x03 \x01(\t\x12\x0c\n\x04make\x18\x04 \x01(\t\x12\x1b\n\x13\x61ndroid_api_version\x18\x05 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CommitUpload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMITUPLOAD']._serialized_start=32
  _globals['_COMMITUPLOAD']._serialized_end=574
  _globals['_COMMITUPLOAD_FIELD1TYPE']._serialized_start=165
  _globals['_COMMITUPLOAD_FIELD1TYPE']._serialized_end=502
  _globals['_COMMITUPLOAD_FIELD1TYPE_FIELD1TYPE']._serialized_start=390
  _globals['_COMMITUPLOAD_FIELD1TYPE_FIELD1TYPE']._serialized_end=434
  _globals['_COMMITUPLOAD_FIELD1TYPE_FIELD4TYPE']._serialized_start=436
  _globals['_COMMITUPLOAD_FIELD1TYPE_FIELD4TYPE']._serialized_end=502
  _globals['_COMMITUPLOAD_FIELD2TYPE']._serialized_start=504
  _globals['_COMMITUPLOAD_FIELD2TYPE']._serialized_end=574
# @@protoc_insertion_point(module_scope)
