# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CreateAlbumResponse.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CreateAlbumResponse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x43reateAlbumResponse.proto\x12\x07gphotos\"\x85\x01\n\x13\x43reateAlbumResponse\x12\x37\n\x06\x66ield1\x18\x01 \x01(\x0b\x32\'.gphotos.CreateAlbumResponse.Field1Type\x12\x0e\n\x06\x66ield2\x18\x02 \x03(\t\x1a%\n\nField1Type\x12\x17\n\x0f\x61lbum_media_key\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CreateAlbumResponse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEALBUMRESPONSE']._serialized_start=39
  _globals['_CREATEALBUMRESPONSE']._serialized_end=172
  _globals['_CREATEALBUMRESPONSE_FIELD1TYPE']._serialized_start=135
  _globals['_CREATEALBUMRESPONSE_FIELD1TYPE']._serialized_end=172
# @@protoc_insertion_point(module_scope)
