# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CreateAlbum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CreateAlbum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x43reateAlbum.proto\x12\x07gphotos\"\xb1\x03\n\x0b\x43reateAlbum\x12\x12\n\nalbum_name\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\x03\x12\x33\n\nmedia_keys\x18\x04 \x03(\x0b\x32\x1f.gphotos.CreateAlbum.Field4Type\x12/\n\x06\x66ield7\x18\x07 \x01(\x0b\x32\x1f.gphotos.CreateAlbum.Field7Type\x12\x34\n\x0b\x64\x65vice_info\x18\x08 \x01(\x0b\x32\x1f.gphotos.CreateAlbum.Field8Type\x1ai\n\nField4Type\x12:\n\x06\x66ield1\x18\x01 \x01(\x0b\x32*.gphotos.CreateAlbum.Field4Type.Field1Type\x1a\x1f\n\nField1Type\x12\x11\n\tmedia_key\x18\x01 \x01(\t\x1a\x1c\n\nField7Type\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x03\x1a\x46\n\nField8Type\x12\r\n\x05model\x18\x03 \x01(\t\x12\x0c\n\x04make\x18\x04 \x01(\t\x12\x1b\n\x13\x61ndroid_api_version\x18\x05 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CreateAlbum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEALBUM']._serialized_start=31
  _globals['_CREATEALBUM']._serialized_end=464
  _globals['_CREATEALBUM_FIELD4TYPE']._serialized_start=257
  _globals['_CREATEALBUM_FIELD4TYPE']._serialized_end=362
  _globals['_CREATEALBUM_FIELD4TYPE_FIELD1TYPE']._serialized_start=331
  _globals['_CREATEALBUM_FIELD4TYPE_FIELD1TYPE']._serialized_end=362
  _globals['_CREATEALBUM_FIELD7TYPE']._serialized_start=364
  _globals['_CREATEALBUM_FIELD7TYPE']._serialized_end=392
  _globals['_CREATEALBUM_FIELD8TYPE']._serialized_start=394
  _globals['_CREATEALBUM_FIELD8TYPE']._serialized_end=464
# @@protoc_insertion_point(module_scope)
