# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HashCheck.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'HashCheck.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fHashCheck.proto\x12\x07gphotos\"\xec\x01\n\tHashCheck\x12-\n\x06\x66ield1\x18\x01 \x01(\x0b\x32\x1d.gphotos.HashCheck.Field1Type\x1a\xaf\x01\n\nField1Type\x12\x38\n\x06\x66ield1\x18\x01 \x01(\x0b\x32(.gphotos.HashCheck.Field1Type.Field1Type\x12\x38\n\x06\x66ield2\x18\x02 \x01(\x0b\x32(.gphotos.HashCheck.Field1Type.Field2Type\x1a\x1f\n\nField1Type\x12\x11\n\tsha1_hash\x18\x01 \x01(\x0c\x1a\x0c\n\nField2Typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HashCheck_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HASHCHECK']._serialized_start=29
  _globals['_HASHCHECK']._serialized_end=265
  _globals['_HASHCHECK_FIELD1TYPE']._serialized_start=90
  _globals['_HASHCHECK_FIELD1TYPE']._serialized_end=265
  _globals['_HASHCHECK_FIELD1TYPE_FIELD1TYPE']._serialized_start=220
  _globals['_HASHCHECK_FIELD1TYPE_FIELD1TYPE']._serialized_end=251
  _globals['_HASHCHECK_FIELD1TYPE_FIELD2TYPE']._serialized_start=253
  _globals['_HASHCHECK_FIELD1TYPE_FIELD2TYPE']._serialized_end=265
# @@protoc_insertion_point(module_scope)
