# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RemoteMatches.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'RemoteMatches.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13RemoteMatches.proto\x12\x07gphotos\"\xf6\x04\n\rRemoteMatches\x12\x31\n\x06\x66ield1\x18\x01 \x01(\x0b\x32!.gphotos.RemoteMatches.Field1Type\x1a\xb1\x04\n\nField1Type\x12<\n\x06\x66ield2\x18\x02 \x01(\x0b\x32,.gphotos.RemoteMatches.Field1Type.Field2Type\x1a\xe4\x03\n\nField2Type\x12G\n\x06\x66ield1\x18\x01 \x01(\x0b\x32\x37.gphotos.RemoteMatches.Field1Type.Field2Type.Field1Type\x12G\n\x06\x66ield2\x18\x02 \x01(\x0b\x32\x37.gphotos.RemoteMatches.Field1Type.Field2Type.Field2Type\x1a\x1f\n\nField1Type\x12\x11\n\tsha1_hash\x18\x01 \x01(\x0c\x1a\xa2\x02\n\nField2Type\x12\x11\n\tmedia_key\x18\x01 \x01(\t\x12R\n\x06\x66ield6\x18\x06 \x01(\x0b\x32\x42.gphotos.RemoteMatches.Field1Type.Field2Type.Field2Type.Field6Type\x1a\xac\x01\n\nField6Type\x12\x11\n\tmedia_key\x18\x01 \x01(\t\x12]\n\x06\x66ield2\x18\x02 \x01(\x0b\x32M.gphotos.RemoteMatches.Field1Type.Field2Type.Field2Type.Field6Type.Field2Type\x1a,\n\nField2Type\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\t\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RemoteMatches_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REMOTEMATCHES']._serialized_start=33
  _globals['_REMOTEMATCHES']._serialized_end=663
  _globals['_REMOTEMATCHES_FIELD1TYPE']._serialized_start=102
  _globals['_REMOTEMATCHES_FIELD1TYPE']._serialized_end=663
  _globals['_REMOTEMATCHES_FIELD1TYPE_FIELD2TYPE']._serialized_start=179
  _globals['_REMOTEMATCHES_FIELD1TYPE_FIELD2TYPE']._serialized_end=663
  _globals['_REMOTEMATCHES_FIELD1TYPE_FIELD2TYPE_FIELD1TYPE']._serialized_start=339
  _globals['_REMOTEMATCHES_FIELD1TYPE_FIELD2TYPE_FIELD1TYPE']._serialized_end=370
  _globals['_REMOTEMATCHES_FIELD1TYPE_FIELD2TYPE_FIELD2TYPE']._serialized_start=373
  _globals['_REMOTEMATCHES_FIELD1TYPE_FIELD2TYPE_FIELD2TYPE']._serialized_end=663
  _globals['_REMOTEMATCHES_FIELD1TYPE_FIELD2TYPE_FIELD2TYPE_FIELD6TYPE']._serialized_start=491
  _globals['_REMOTEMATCHES_FIELD1TYPE_FIELD2TYPE_FIELD2TYPE_FIELD6TYPE']._serialized_end=663
  _globals['_REMOTEMATCHES_FIELD1TYPE_FIELD2TYPE_FIELD2TYPE_FIELD6TYPE_FIELD2TYPE']._serialized_start=619
  _globals['_REMOTEMATCHES_FIELD1TYPE_FIELD2TYPE_FIELD2TYPE_FIELD6TYPE_FIELD2TYPE']._serialized_end=663
# @@protoc_insertion_point(module_scope)
